import type { NextPage } from "next";
import Head from "next/head";
import Ordering from "../components/Ordering";
import Switch from "../components/Switch";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Ordering />
      </section>
      <section style={{ marginTop: "50px" }}>
        <Switch />
      </section>
    </div>
  );
};

export default Home;
